### ISSUE TITLE
Change channels.yml to list of connections

### ISSUE THREAD

**Issue by Bjornskjald** [miscord/miscord#293]
Instead of this:
```yaml
'12345': '67890'
'555':
- '123'
- '456'
- '789'
```

it would be something like this:
```yaml
connection_a:
- type: discord
  id: '12345'
- type: messenger
  id: '67890'

connection_b:
- type: discord
  id: '555'
- type: messenger
  id: '123'
- type: messenger
  id: '456'
- type: messenger
  id: '789'
```

also, graphical configurator for this.

also:
```yaml
connection_c:
- type: discord
  id: '12345'
- type: messenger
  id: '67890'
  readonly: true
```
